# serverless.yml

service: avconnect-service

provider:
    name: aws
    runtime: nodejs14.x
    stage: dev
    region: ap-south-1
    lambdaHashingVersion: 20201221

package:
    patterns:
        - '!*'
        - '!src/**'
        - 'node_modules'
        - 'build'
        - '.env'
functions:
    app:
        handler: ./build/serverless.handler
        events:
            - http: ANY /
            - http: 'ANY {proxy+}'
