# serverless.yml

service: avconnect-service

provider:
    name: aws
    runtime: nodejs14.x
    stage: dev
    region: ap-south-1
    lambdaHashingVersion: 20201221
    apiGateway:
        binaryMediaTypes:
            - '*/*'

package:
    patterns:
        - '!*'
        - '!src/**'
        - 'node_modules'
        - 'build'
        - '.env'

functions:
    app:
        handler: ./build/serverless.handler
        events:
            - http:
                  path: ANY /
                  request:
                      contentHandling: CONVERT_TO_TEXT
                  response:
                      contentHandling: CONVERT_TO_TEXT
            - http: 'ANY {proxy+}'
