name: AVConnect Backend Deployment

on:
    push:
        branches: [main, dev]
    workflow_dispatch:

jobs:
    serverless-deployment:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Initializing prod environment
              if: github.ref == 'refs/heads/main'
              run: echo "ENVIRONMENT=PROD" >> $GITHUB_ENV

            - name: Initializing dev environment
              if: github.ref == 'refs/heads/dev'
              run: echo "ENVIRONMENT=DEV" >> $GITHUB_ENV

            - name: Setup environment variables
              run: |
                  touch .env
                  echo "AWS_KEY=${{ secrets[format('{0}_AWS_KEY', env.ENVIRONMENT)] }}" >> $GITHUB_ENV >> .env
                  echo "AWS_SECRET=${{ secrets[format('{0}_AWS_SECRET', env.ENVIRONMENT)] }}" >> $GITHUB_ENV >> .env
                  echo "AWS_REGION=${{ secrets[format('{0}_AWS_REGION', env.ENVIRONMENT)] }}" >> $GITHUB_ENV >> .env
                  echo "COGNITO_CLIENT_DOMAIN=${{ secrets[format('{0}_COGNITO_CLIENT_DOMAIN', env.ENVIRONMENT)] }}" >> $GITHUB_ENV >> .env
                  echo "COGNITO_ISSUER_URL=${{ secrets[format('{0}_COGNITO_ISSUER_URL', env.ENVIRONMENT)] }}" >> $GITHUB_ENV >> .env
                  echo "S3_BUCKET=${{ secrets[format('{0}_S3_BUCKET', env.ENVIRONMENT)] }}" >> $GITHUB_ENV >> .env
                  cat .env

            - name: Install node packages
              run: npm install

            - name: Code Lint
              run: npm run lint:fix

            - name: Generating build
              run: npm run build

            - name: Configure AWS credentials
              run: npm run serverless:credentials

            - name: Production deployment
              if: github.ref == 'refs/heads/main'
              run: npm run serverless:deploy:prod

            - name: Development deployment
              if: github.ref == 'refs/heads/dev'
              run: npm run serverless:deploy:dev
