name: AVConnect Backend Deployment

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    serverless-deployment:
        runs-on: ubuntu-latest
        env:
            AWS_KEY: ${{ secrets.AWS_KEY }}
            AWS_SECRET: ${{ secrets.AWS_SECRET }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            COGNITO_CLIENT_DOMAIN: ${{ secrets.COGNITO_CLIENT_DOMAIN }}
            COGNITO_ISSUER_URL: ${{ secrets.COGNITO_ISSUER_URL }}
            S3_BUCKET: ${{ secrets.S3_BUCKET }}

        steps:
            - uses: actions/checkout@v2

            - name: Intialize .env
              run: |
                  touch .env
                  echo "AWS_KEY=${AWS_KEY}" >> .env
                  echo "AWS_SECRET=${AWS_SECRET}" >> .env
                  echo "AWS_REGION=${AWS_REGION}" >> .env
                  echo "COGNITO_CLIENT_DOMAIN=${COGNITO_CLIENT_DOMAIN}" >> .env
                  echo "COGNITO_ISSUER_URL=${COGNITO_ISSUER_URL}" >> .env
                  echo "S3_BUCKET=${S3_BUCKET}" >> .env
                  cat .env
            # Runs a single command using the runners shell
            - name: Install node packages
              run: npm install

            - name: Code Lint
              run: npm run lint:fix

            - name: Generating build
              run: npm run build

            - name: Deploy to AWS
              run: |
                  npm run serverless:credentials
                  npm run serverless:deploy
