name: AVConnect Backend Deployment

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    serverless-deployment:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Initializing prod environment
              if: github.ref == 'refs/heads/main'
              env:
                  ENVIRONMENT: PROD
              run: export ENVIRONMENT=PROD

            - name: Initializing dev environment
              if: github.ref == 'refs/heads/dev'
              env:
                  ENVIRONMENT: DEV
              run: echo "Configured dev environment"

            - name: Setup environment variables
              env:
                  AWS_KEY: ${{ secrets[format('{0}_AWS_KEY', env.ENVIRONMENT)] }}
                  AWS_SECRET: ${{ secrets[format('{0}_AWS_SECRET', env.ENVIRONMENT)] }}
                  AWS_REGION: ${{ secrets[format('{0}_AWS_REGION', env.ENVIRONMENT)] }}
                  COGNITO_CLIENT_DOMAIN: ${{ secrets[format('{0}_COGNITO_CLIENT_DOMAIN', env.ENVIRONMENT)] }}
                  COGNITO_ISSUER_URL: ${{ secrets[format('{0}_COGNITO_ISSUER_URL', env.ENVIRONMENT)] }}
                  S3_BUCKET: ${{ secrets[format('{0}_S3_BUCKET', env.ENVIRONMENT)] }}
              run: |
                  touch .env
                  echo "AWS_KEY=${AWS_KEY}" >> .env
                  echo "AWS_SECRET=${AWS_SECRET}" >> .env
                  echo "AWS_REGION=${AWS_REGION}" >> .env
                  echo "COGNITO_CLIENT_DOMAIN=${COGNITO_CLIENT_DOMAIN}" >> .env
                  echo "COGNITO_ISSUER_URL=${COGNITO_ISSUER_URL}" >> .env
                  echo "S3_BUCKET=${S3_BUCKET}" >> .env
                  cat .env

            - name: Install node packages
              run: npm install

            - name: Code Lint
              run: npm run lint:fix

            - name: Generating build
              run: npm run build

            - name: Configure AWS credentials
              run: npm run serverless:credentials

            - name: Production deployment
              if: github.ref == 'refs/heads/main'
              run: npm run serverless:deploy:prod

            - name: Development deployment
              if: github.ref == 'refs/heads/dev'
              run: npm run serverless:deploy:dev
